extends: eval_airsim_dataset_release.yaml
adapter_ckpt: D:/VoLN_dataset/VoLN-UAV-runs/adapter_no_align_paper/adapter_best.pt
planner_ckpt: D:/VoLN_dataset/VoLN-UAV-runs/planner_no_align_paper/planner_best.pt
work_dir: D:/VoLN_dataset/VoLN-UAV-runs/eval_airsim_no_align_paper
model:
  ablation: no_align
