extends: eval_airsim_dataset_release.yaml
adapter_ckpt: null
planner_ckpt: D:/VoLN_dataset/VoLN-UAV-runs/planner_clip_input_paper/planner_best.pt
work_dir: D:/VoLN_dataset/VoLN-UAV-runs/eval_airsim_clip_input_paper
model:
  ablation: clip_input
  vision_input: clip
